services:
  - type: web
    name: team-task-manager
    env: node
    plan: free
    branch: main
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: MONGO_URI
        value: "<YOUR_MONGO_URI>"
      - key: JWT_SECRET
        value: "<YOUR_JWT_SECRET>"
